name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # Explicitly grant write permissions to the GITHUB_TOKEN
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools fakeroot

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Build and Release
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            bunx electron-builder --linux --publish always
          elif [ "$RUNNER_OS" == "Windows" ]; then
            bunx electron-builder --win --publish always
          elif [ "$RUNNER_OS" == "macOS" ]; then
            bunx electron-builder --mac --publish always
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
